version: '3.8'

services:
  bot:
    container_name: bot
    build: ./
    command: python main.py
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tg_bot_template
volumes:
  postgres_data: